/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Customer;
import Business.CustomerDirectory;
import Business.Flight;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jumin
 */
public class BookTickets extends javax.swing.JPanel {

    /**
     * Creates new form SearchFlight
     */
    JPanel CardSequenceJPanel;
    private CustomerDirectory customerDirectory;
    private int pos = -1;
    private int row = -1;
    

    BookTickets(JPanel CardSequenceJPanel, CustomerDirectory customerDirectory) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.customerDirectory = customerDirectory;
        setSeatPosition();
        jRow.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFlightNumber = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jPos = new javax.swing.JComboBox<>();
        jRow = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnSelectPos = new javax.swing.JButton();
        btnSelectRow = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Flight Number:");

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Book Tickets");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Name:");

        jPos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Seat:");

        btnSelectPos.setText("Select Position");
        btnSelectPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPosActionPerformed(evt);
            }
        });

        btnSelectRow.setText("Select Row");
        btnSelectRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectRowActionPerformed(evt);
            }
        });

        btnClear.setText("Clear Seat Choice");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPos, 0, 115, Short.MAX_VALUE)
                            .addComponent(jRow, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelectRow, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelectPos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnSelectPos))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectRow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnClear)
                .addGap(30, 30, 30)
                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.CardSequenceJPanel.remove(this);
        CardLayout layout=(CardLayout) this.CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        if (txtFlightNumber == null|| txtFlightNumber.equals("")) {
            JOptionPane.showMessageDialog(null, "Flight number can't be empty!");
            return;
        }
        if (!flightPatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Flight number should be in the form like HU481");
            return;
        }
        if (txtName == null|| txtName.equals("")) {
            JOptionPane.showMessageDialog(null, "Passanger name can't be empty!");
            return;
        }
        for (int k=0; k<customerDirectory.getCustomerList().size(); k++) {
            if (txtFlightNumber.getText().equals(customerDirectory.getCustomerList().get(k).getFlightNumber()) && txtName.getText().equals(customerDirectory.getCustomerList().get(k).getName())) {
            JOptionPane.showMessageDialog(null, "This customer has already booked a  ticket for this flight!");
            return;
            }
        }
        if (pos==-1||row==-1) {
            JOptionPane.showMessageDialog(null, "Please select a seat!");
        }
        Customer customer = new Customer();
        customer.setFlightNumber(txtFlightNumber.getText());
        customer.setName(txtName.getText());
        int[] temp = new int[] {pos,row};
        customer.setSeat(temp);
        customerDirectory.getCustomerList().add(customer);
        
        JOptionPane.showMessageDialog(null, "You have successfully booked a ticket!");
        txtFlightNumber.setText("");
        txtName.setText("");
        jRow.setEnabled(false);
        jRow.removeAllItems();
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnSelectPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPosActionPerformed
        // TODO add your handling code here:
        pos = jPos.getSelectedIndex();
        if (txtFlightNumber == null|| txtFlightNumber.equals("")) {
            JOptionPane.showMessageDialog(null, "Flight number can't be empty!");
            return;
        }
        if (!flightPatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Flight number should be in the form like HU481");
            return;
        }
        if (pos==-1) {
            JOptionPane.showMessageDialog(null, "Please select a position first!");
            return;
        }
        setSeatRow();
        jRow.setEnabled(true);  
    }//GEN-LAST:event_btnSelectPosActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        jRow.removeAllItems();
        jRow.setEnabled(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSelectRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectRowActionPerformed
        // TODO add your handling code here: 
        for (int n=0; n<customerDirectory.getCustomerList().size(); n++) {
                int[] seatNum=customerDirectory.getCustomerList().get(n).getSeat();
                if(txtFlightNumber.getText().equals(customerDirectory.getCustomerList().get(n).getFlightNumber()) && seatNum[0]==jPos.getSelectedIndex()&& seatNum[1]==jRow.getSelectedIndex()) {
                    JOptionPane.showMessageDialog(null, "This seat has already been booked!");
                    return;
                }
        }
         if (pos==-1) {
            JOptionPane.showMessageDialog(null, "Please select a row!");
            return;
        }
         row = jRow.getSelectedIndex();
        JOptionPane.showMessageDialog(null, "You have successfully selected a seat!");
    }//GEN-LAST:event_btnSelectRowActionPerformed

    private boolean flightPatternCorrect() {
        Pattern p = Pattern.compile("^[A-Z][A-Z][0-9][0-9][0-9]$");
        Matcher m = p.matcher(txtFlightNumber.getText());
        boolean b = m.matches();
        return b;
    }
    
    private void setSeatPosition() {
        jPos.removeAllItems();
        jPos.addItem("Left window");
        jPos.addItem("Left middle");
        jPos.addItem("Left aisle");
        jPos.addItem("Right aisle");
        jPos.addItem("Right middle");
        jPos.addItem("Right window");
    }
    
    private void setSeatRow() {
        jRow.removeAllItems();
        int judgevar = 0;
        for (int i=0; i<25; i++) { 
            for (int j=0; j<customerDirectory.getCustomerList().size(); j++) {
                int[] seatNum=customerDirectory.getCustomerList().get(j).getSeat();
                if(txtFlightNumber.getText().equals(customerDirectory.getCustomerList().get(j).getFlightNumber()) && seatNum[0]==jPos.getSelectedIndex()&& seatNum[1]==i) {
                    judgevar = 1;
                }
            }
            if (judgevar==0) {
                jRow.addItem(String.valueOf(i+1));
            }
            else jRow.addItem(String.valueOf(i+1)+ "  Booked");
            judgevar=0;
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSelectPos;
    private javax.swing.JButton btnSelectRow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jPos;
    private javax.swing.JComboBox<String> jRow;
    private javax.swing.JTextField txtFlightNumber;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
