/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Customer;
import Business.CustomerDirectory;
import Business.Flight;
import Business.FlightDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jumin
 */
public class CustomerView extends javax.swing.JPanel {

    /**
     * Creates new form customerView
     */
    JPanel CardSequenceJPanel;
    private CustomerDirectory customerDirectory;
    private FlightDirectory flightDirectory;
    
    CustomerView(JPanel CardSequenceJPanel, CustomerDirectory customerDirectory, FlightDirectory flightDirectory) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.customerDirectory = customerDirectory;
        this.flightDirectory = flightDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNewFlight = new javax.swing.JTable();
        txtCustomerName = new javax.swing.JTextField();
        btnSearchbyName = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("View Flight");

        tblNewFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Take off Date", "Take off time", "Arrival", "Departure", "Destination", "Seat Positon", "Seat Row"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNewFlight);
        if (tblNewFlight.getColumnModel().getColumnCount() > 0) {
            tblNewFlight.getColumnModel().getColumn(0).setResizable(false);
            tblNewFlight.getColumnModel().getColumn(1).setResizable(false);
            tblNewFlight.getColumnModel().getColumn(2).setResizable(false);
            tblNewFlight.getColumnModel().getColumn(3).setResizable(false);
            tblNewFlight.getColumnModel().getColumn(4).setResizable(false);
            tblNewFlight.getColumnModel().getColumn(5).setResizable(false);
            tblNewFlight.getColumnModel().getColumn(6).setResizable(false);
        }

        btnSearchbyName.setText("Search by Name");
        btnSearchbyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbyNameActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel1.setText("Please input your name here:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnSearchbyName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSearchbyName))
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.CardSequenceJPanel.remove(this);
        CardLayout layout=(CardLayout) CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchbyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbyNameActionPerformed
        // TODO add your handling code here:
        if (txtCustomerName == null|| txtCustomerName.equals("")) {
            JOptionPane.showMessageDialog(null, "Customer cannot be empty!");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tblNewFlight.getModel();
        dtm.setRowCount(0);
        for (Customer customer : customerDirectory.getCustomerList()) {
            Object[] row = new Object[8];
            if (customer.getName().equals(txtCustomerName.getText())) {
                row[0] = customer.getFlightNumber();
                for(int i=0; i<flightDirectory.getFlightList().size(); i++) {
                    if(customer.getFlightNumber().equals(flightDirectory.getFlightList().get(i).getFlightNumber())) {
                        row[1] = flightDirectory.getFlightList().get(i).getTakeOffDate();
                        row[2] = flightDirectory.getFlightList().get(i).getTakeOffTime();
                        row[3] = flightDirectory.getFlightList().get(i).getArrival();
                        row[4] = flightDirectory.getFlightList().get(i).getDeparture();
                        row[5] = flightDirectory.getFlightList().get(i).getDestination();
                    }
                }
            int[] temp = new int[2];
            temp = customer.getSeat();
            if (temp[0]==0) row[6] = "Left window";
            else if (temp[0]==1) row[6] = "Left middle";   
            else if (temp[0]==2) row[6] = "Left aisle"; 
            else if (temp[0]==3) row[6] = "Right window"; 
            else if (temp[0]==4) row[6] = "Right middle"; 
            else if (temp[0]==5) row[6] = "Right window"; 
            row[7] = temp[1]+1;
            dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_btnSearchbyNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearchbyName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNewFlight;
    private javax.swing.JTextField txtCustomerName;
    // End of variables declaration//GEN-END:variables
}
